export const products = [
  {
    ProductID: '1',
    ProductName: 'Test 1',
    Product: {
      ProductID: '1',
      ProductName: 'Test 1',
    },
    SupplierID: 1,
    CategoryID: 1,
    QuantityPerUnit: '10 boxes x 20 bags',
    UnitPrice: 18.0,
    UnitsInStock: 39,
    UnitsOnOrder: 0,
    ReorderLevel: 10,
    Discontinued: false,
    List: [
      'Beverages',
      'Condiments',
      'Produce',
      'MeatPoultry',
      'Dairy',
      'Seafood',
    ],
  },
  {
    ProductID: '2',
    ProductName: 'Test 2',
    Product: {
      ProductID: '2',
      ProductName: 'Test 2',
    },
    SupplierID: 1,
    CategoryID: 1,
    QuantityPerUnit: '24 - 12 oz bottles',
    UnitPrice: 19.0,
    UnitsInStock: 17,
    UnitsOnOrder: 40,
    ReorderLevel: 25,
    Discontinued: false,
    List: [
      'Beverages',
      'Condiments',
      'Produce',
      'MeatPoultry',
      'Dairy',
      'Seafood',
    ],
  },
  {
    ProductID: '2',
    ProductName: 'Test 2',
    Product: {
      ProductID: '2',
      ProductName: 'Test 2',
    },
    SupplierID: 1,
    CategoryID: 2,
    QuantityPerUnit: '12 - 550 ml bottles',
    UnitPrice: 10.0,
    UnitsInStock: 13,
    UnitsOnOrder: 70,
    ReorderLevel: 25,
    Discontinued: false,
    List: [
      'Beverages',
      'Condiments',
      'Produce',
      'MeatPoultry',
      'Dairy',
      'Seafood',
    ],
  },
  {
    ProductID: '2',
    ProductName: 'Test 2',
    Product: {
      ProductID: '2',
      ProductName: 'Test 2',
    },
    SupplierID: 2,
    CategoryID: 2,
    QuantityPerUnit: '48 - 6 oz jars',
    UnitPrice: 22.0,
    UnitsInStock: 53,
    UnitsOnOrder: 0,
    ReorderLevel: 0,
    Discontinued: false,
    List: [
      'Beverages',
      'Condiments',
      'Produce',
      'MeatPoultry',
      'Dairy',
      'Seafood',
    ],
  },
];
